"""Private Cloudflare R2 storage for uploaded resumes.

Access model
------------
All objects are stored in a **private** R2 bucket with no public-access
policy.  The only way to read a resume is through a short-lived, signed URL
generated by :meth:`ResumeStorage.get_presigned_download_url`, which is itself
protected behind the ``get_current_user`` JWT dependency in the API layer.

Ownership enforcement
---------------------
Every object key is namespaced by user-ID:  ``resumes/<user_id>/<uuid>.pdf``.
Before generating any presigned URL the ``verify_owner`` helper asserts that
the stored key actually belongs to the requesting user, making it impossible
for one authenticated user to obtain a download link for another user's resume
even if they somehow know that user's internal database ID.
"""

import asyncio
from functools import cached_property
from uuid import uuid4

import boto3
from botocore.client import BaseClient

from config.settings import settings


class R2StorageError(RuntimeError):
    """Raised when resume object storage is unavailable or fails."""


class ResumeStorage:
    """S3-compatible client wrapper for the application's private R2 bucket."""

    def is_configured(self) -> bool:
        """Check if Cloudflare R2 is configured with non-placeholder credentials."""
        required = [
            settings.r2_account_id,
            settings.r2_access_key_id,
            settings.r2_secret_access_key,
            settings.r2_bucket_name,
        ]
        if not all(required):
            return False
        for val in required:
            val_str = str(val).strip()
            if (
                val_str.startswith("<")
                or "account-id" in val_str
                or "access-key-id" in val_str
                or "secret-access-key" in val_str
            ):
                return False
        return True

    def _validate_settings(self) -> None:
        if not self.is_configured():
            raise R2StorageError(
                "Cloudflare R2 is not configured or contains placeholder credentials."
            )

    @cached_property
    def _client(self) -> BaseClient:
        self._validate_settings()
        endpoint_url = (
            settings.r2_endpoint_url
            if settings.r2_endpoint_url
            and "cloudflarestorage.com" in settings.r2_endpoint_url
            else f"https://{settings.r2_account_id}.r2.cloudflarestorage.com"
        )
        return boto3.client(
            "s3",
            endpoint_url=endpoint_url,
            aws_access_key_id=settings.r2_access_key_id,
            aws_secret_access_key=settings.r2_secret_access_key,
            region_name="auto",
        )

    async def upload_resume(self, user_id: int, file_bytes: bytes) -> str:
        """Store a PDF privately and return its opaque object key."""
        self._validate_settings()
        key = f"resumes/{user_id}/{uuid4().hex}.pdf"
        try:
            await asyncio.to_thread(
                self._client.put_object,
                Bucket=settings.r2_bucket_name,
                Key=key,
                Body=file_bytes,
                ContentType="application/pdf",
            )
        except Exception as exc:
            raise R2StorageError("Failed to upload resume to Cloudflare R2") from exc
        return key

    async def delete_resume(self, storage_key: str) -> None:
        """Delete a private resume object by key."""
        if not storage_key:
            return
        self._validate_settings()
        try:
            await asyncio.to_thread(
                self._client.delete_object,
                Bucket=settings.r2_bucket_name,
                Key=storage_key,
            )
        except Exception as exc:
            raise R2StorageError("Failed to delete resume from Cloudflare R2") from exc

    # ------------------------------------------------------------------
    # Ownership guard
    # ------------------------------------------------------------------

    @staticmethod
    def verify_owner(storage_key: str, user_id: int) -> None:
        """Assert the storage key belongs to *user_id*.

        Object keys are always stored as ``resumes/<user_id>/<uuid>.pdf``.
        This prevents one authenticated user from ever obtaining a signed URL
        that points to another user's resume.

        Raises:
            R2StorageError: if the key's embedded user-ID does not match.
        """
        # Local dev placeholder keys are safe to skip (they're never real URLs)
        if storage_key.startswith("local/"):
            return
        # Expected shape: resumes/<user_id>/<uuid>.pdf
        parts = storage_key.split("/")
        if len(parts) < 2 or parts[0] != "resumes":
            raise R2StorageError(
                f"Malformed storage key '{storage_key}': expected 'resumes/<user_id>/...' prefix."
            )
        try:
            key_owner_id = int(parts[1])
        except ValueError:
            raise R2StorageError(
                f"Malformed storage key '{storage_key}': user-ID segment is not numeric."
            )
        if key_owner_id != user_id:
            raise R2StorageError(
                "Access denied: the requested resume does not belong to the current user."
            )

    # ------------------------------------------------------------------
    # Presigned download URL
    # ------------------------------------------------------------------

    async def get_presigned_download_url(
        self,
        storage_key: str,
        user_id: int,
        file_name: str = "resume.pdf",
        expires_in: int = 300,
    ) -> str:
        """Generate a short-lived (default 5 min) pre-signed URL for private downloading.

        Ownership is verified before the URL is issued: the embedded user-ID
        in *storage_key* must match *user_id* or an :exc:`R2StorageError` is
        raised.  The URL is signed for the requesting user's session only —
        it cannot be guessed or brute-forced because the object key contains a
        random UUID segment.

        Args:
            storage_key: The S3 object key (``resumes/<user_id>/<uuid>.pdf``).
            user_id:     The ID of the authenticated user requesting the URL.
            file_name:   Original file name used for ``Content-Disposition``.
            expires_in:  URL lifetime in seconds (default 300 / 5 minutes).

        Returns:
            A pre-signed HTTPS URL valid for *expires_in* seconds.
        """
        if not storage_key:
            raise R2StorageError("Storage key is required")
        self._validate_settings()
        self.verify_owner(storage_key, user_id)
        safe_name = file_name.replace('"', "")  # strip any embedded quotes
        try:
            url = await asyncio.to_thread(
                self._client.generate_presigned_url,
                "get_object",
                Params={
                    "Bucket": settings.r2_bucket_name,
                    "Key": storage_key,
                    "ResponseContentType": "application/pdf",
                    # Serve inline (opens in browser) with original filename
                    "ResponseContentDisposition": f'inline; filename="{safe_name}"',
                },
                ExpiresIn=expires_in,
            )
            return url
        except R2StorageError:
            raise
        except Exception as exc:
            raise R2StorageError("Failed to generate pre-signed URL") from exc


resume_storage = ResumeStorage()
