job_config:
  default_expiry_days: 30

scraper_config:
  job_title: "Software Engineer Intern"
  locations:
    - India
  job_type:
    - INTERNSHIP
  experience_level:
    - INTERNSHIP
  limit: 20
  headless: true

admin_config:
  admin_emails:
    - "admin@luckylinux.dev"
    - "luckyverma.dev@gmail.com"
