"""create raw_jobs

Revision ID: 33911cca3577
Revises: 
Create Date: 2026-06-05 15:49:10.051663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33911cca3577'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('date_posted', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_jobs_company'), 'raw_jobs', ['company'], unique=False)
    op.create_index(op.f('ix_raw_jobs_content_hash'), 'raw_jobs', ['content_hash'], unique=True)
    op.create_index(op.f('ix_raw_jobs_source'), 'raw_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_raw_jobs_title'), 'raw_jobs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_jobs_title'), table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_source'), table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_content_hash'), table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_company'), table_name='raw_jobs')
    op.drop_table('raw_jobs')
    # ### end Alembic commands ###
