"""add last_date_to_apply to processed_jobs

Revision ID: 3df8f91d0aa9
Revises: f408ce98dbe1
Create Date: 2026-08-23 11:40:36.504475

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3df8f91d0aa9"
down_revision: Union[str, Sequence[str], None] = "f408ce98dbe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processed_jobs", sa.Column("last_date_to_apply", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processed_jobs", "last_date_to_apply")
    # ### end Alembic commands ###
