"""create processed_jobs

Revision ID: 68cc82b16b5f
Revises: 33911cca3577
Create Date: 2026-06-27 21:22:46.443837

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68cc82b16b5f"
down_revision: Union[str, Sequence[str], None] = "33911cca3577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_job_id", sa.Integer(), nullable=False),
        sa.Column("job_title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("salary", sa.String(length=100), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("employment_type", sa.String(length=100), nullable=True),
        sa.Column("job_description", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["raw_job_id"], ["raw_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_jobs_company"), "processed_jobs", ["company"], unique=False
    )
    op.create_index(
        op.f("ix_processed_jobs_job_title"),
        "processed_jobs",
        ["job_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_jobs_raw_job_id"),
        "processed_jobs",
        ["raw_job_id"],
        unique=True,
    )
    op.add_column(
        "raw_jobs",
        sa.Column(
            "processing_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_raw_jobs_processing_status"),
        "raw_jobs",
        ["processing_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_jobs_processing_status"), table_name="raw_jobs")
    op.drop_column("raw_jobs", "processing_status")
    op.drop_index(op.f("ix_processed_jobs_raw_job_id"), table_name="processed_jobs")
    op.drop_index(op.f("ix_processed_jobs_job_title"), table_name="processed_jobs")
    op.drop_index(op.f("ix_processed_jobs_company"), table_name="processed_jobs")
    op.drop_table("processed_jobs")
    # ### end Alembic commands ###
