"""add_job_and_user_embeddings_pgvector

Revision ID: 6a676ac7bf67
Revises: 48ce7312f768
Create Date: 2026-08-23 17:56:14.493105

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a676ac7bf67"
down_revision: Union[str, Sequence[str], None] = "48ce7312f768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column(
        "processed_jobs",
        sa.Column("embedding", pgvector.sqlalchemy.Vector(768), nullable=True),
    )
    op.add_column(
        "processed_jobs",
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "preference_embedding", pgvector.sqlalchemy.Vector(768), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("preference_embedding_model", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preference_embedding_model")
    op.drop_column("users", "preference_embedding")
    op.drop_column("processed_jobs", "embedding_model")
    op.drop_column("processed_jobs", "embedding")
    # ### end Alembic commands ###
