"""create users table

Revision ID: a028d6f2e27e
Revises: 68cc82b16b5f
Create Date: 2026-06-28 17:40:44.681008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a028d6f2e27e"
down_revision: Union[str, Sequence[str], None] = "68cc82b16b5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth0_sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("title", sa.String(length=255), server_default="", nullable=False),
        sa.Column("location", sa.String(length=255), server_default="", nullable=False),
        sa.Column("bio", sa.String(length=1000), server_default="", nullable=False),
        sa.Column(
            "years_of_experience", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("skills", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("preferred_roles", sa.JSON(), server_default="[]", nullable=False),
        sa.Column(
            "preferred_locations", sa.JSON(), server_default="[]", nullable=False
        ),
        sa.Column("work_modes", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("min_salary", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "email_verified", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_auth0_sub"), "users", ["auth0_sub"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_auth0_sub"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
