"""add_willing_to_relocate_to_users

Revision ID: b4bf1fe280c5
Revises: f4de408c0c82
Create Date: 2026-08-25 11:54:00.887891

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4bf1fe280c5"
down_revision: Union[str, Sequence[str], None] = "f4de408c0c82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "willing_to_relocate", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "willing_to_relocate")
    # ### end Alembic commands ###
