"""add_apply_url_contact_fields_and_company_contacts_table

Revision ID: e20c2bd928e7
Revises: 6a676ac7bf67
Create Date: 2026-08-25 00:30:25.023526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e20c2bd928e7"
down_revision: Union[str, Sequence[str], None] = "6a676ac7bf67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_key", sa.String(length=300), nullable=False),
        sa.Column("company_name", sa.String(length=300), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=True),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_role", sa.String(length=200), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("linkedin_url", sa.String(length=2048), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_contacts_company_key"),
        "company_contacts",
        ["company_key"],
        unique=True,
    )
    op.add_column(
        "processed_jobs", sa.Column("apply_url", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "processed_jobs",
        sa.Column("contact_email", sa.String(length=320), nullable=True),
    )
    op.add_column(
        "processed_jobs",
        sa.Column("contact_name", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "processed_jobs",
        sa.Column("contact_role", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processed_jobs", "contact_role")
    op.drop_column("processed_jobs", "contact_name")
    op.drop_column("processed_jobs", "contact_email")
    op.drop_column("processed_jobs", "apply_url")
    op.drop_index(
        op.f("ix_company_contacts_company_key"), table_name="company_contacts"
    )
    op.drop_table("company_contacts")
    # ### end Alembic commands ###
