"""initial_supabase_baseline

Revision ID: f408ce98dbe1
Revises:
Create Date: 2026-08-17 12:16:55.885999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f408ce98dbe1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("date_posted", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("link", sa.String(length=2048), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.Column(
            "processing_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raw_jobs_company"), "raw_jobs", ["company"], unique=False)
    op.create_index(
        op.f("ix_raw_jobs_content_hash"), "raw_jobs", ["content_hash"], unique=True
    )
    op.create_index(
        op.f("ix_raw_jobs_processing_status"),
        "raw_jobs",
        ["processing_status"],
        unique=False,
    )
    op.create_index(op.f("ix_raw_jobs_source"), "raw_jobs", ["source"], unique=False)
    op.create_index(op.f("ix_raw_jobs_title"), "raw_jobs", ["title"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth0_sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("role", sa.String(length=50), server_default="user", nullable=False),
        sa.Column("title", sa.String(length=255), server_default="", nullable=False),
        sa.Column("location", sa.String(length=255), server_default="", nullable=False),
        sa.Column("bio", sa.String(length=1000), server_default="", nullable=False),
        sa.Column(
            "years_of_experience", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("skills", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("preferred_roles", sa.JSON(), server_default="[]", nullable=False),
        sa.Column(
            "preferred_locations", sa.JSON(), server_default="[]", nullable=False
        ),
        sa.Column("work_modes", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("min_salary", sa.Integer(), server_default="0", nullable=False),
        sa.Column("resume_file_name", sa.String(length=500), nullable=True),
        sa.Column("resume_storage_key", sa.String(length=1024), nullable=True),
        sa.Column("resume_size_kb", sa.Integer(), nullable=True),
        sa.Column("resume_uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("resume_status", sa.String(length=50), nullable=True),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column(
            "resume_extracted_skills", sa.JSON(), server_default="[]", nullable=False
        ),
        sa.Column("resume_experience_level", sa.String(length=100), nullable=True),
        sa.Column("resume_years_total", sa.Integer(), nullable=True),
        sa.Column("resume_confidence", sa.Float(), nullable=True),
        sa.Column(
            "email_verified", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_auth0_sub"), "users", ["auth0_sub"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "processed_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_job_id", sa.Integer(), nullable=False),
        sa.Column("job_title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("salary", sa.String(length=100), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("employment_type", sa.String(length=100), nullable=True),
        sa.Column("job_description", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["raw_job_id"], ["raw_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_jobs_company"), "processed_jobs", ["company"], unique=False
    )
    op.create_index(
        op.f("ix_processed_jobs_job_title"),
        "processed_jobs",
        ["job_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_jobs_raw_job_id"),
        "processed_jobs",
        ["raw_job_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_jobs_raw_job_id"), table_name="processed_jobs")
    op.drop_index(op.f("ix_processed_jobs_job_title"), table_name="processed_jobs")
    op.drop_index(op.f("ix_processed_jobs_company"), table_name="processed_jobs")
    op.drop_table("processed_jobs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_auth0_sub"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_raw_jobs_title"), table_name="raw_jobs")
    op.drop_index(op.f("ix_raw_jobs_source"), table_name="raw_jobs")
    op.drop_index(op.f("ix_raw_jobs_processing_status"), table_name="raw_jobs")
    op.drop_index(op.f("ix_raw_jobs_content_hash"), table_name="raw_jobs")
    op.drop_index(op.f("ix_raw_jobs_company"), table_name="raw_jobs")
    op.drop_table("raw_jobs")
    # ### end Alembic commands ###
