"""add_job_applications_table

Revision ID: f4de408c0c82
Revises: e20c2bd928e7
Create Date: 2026-08-25 03:04:40.424853

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4de408c0c82"
down_revision: Union[str, Sequence[str], None] = "e20c2bd928e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="applied", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["processed_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_id", name="uq_user_job_application"),
    )
    op.create_index(
        op.f("ix_job_applications_applied_at"),
        "job_applications",
        ["applied_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_applications_job_id"), "job_applications", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_applications_status"), "job_applications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_job_applications_user_id"),
        "job_applications",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_applications_user_id"), table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_status"), table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_job_id"), table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_applied_at"), table_name="job_applications")
    op.drop_table("job_applications")
    # ### end Alembic commands ###
